### ISSUE TITLE
Crash when launching formula

### ISSUE THREAD

**Issue by valentin19** [powerapi-ng/smartwatts-formula#10]
docker run -ti --rm --name powerapi-formula \
      -v "./sensor/:/var/data" powerapi/smartwatts-formula:latest  \
      --input csv  --files /var/data/core,/var/data/msr,/var/data/rapl \
      --output csv --model PowerReport --name power  -d /var/data/power \
      --formula smartwatts \
      --cpu-ratio-base 23 \
      --cpu-ratio-min 10 --cpu-ratio-max 32 --cpu-error-threshold 2.0 \
      --dram-error-threshold 2.0 --disable-dram-formula

'verbose': 0, 'stream': False, 'input': {'csv': {'puller_csv': {'files': ['/var/data/core', '/var/data/msr', '/var/data/rapl'], 'model': 'HWPCReport', 'name': 'puller_csv'}}}, 'output': {'csv': {'power': {'model': 'PowerReport', 'name': 'power', 'directory': '/var/data/power'}}}, 'formula': {'smartwatts': {'disable-cpu-formula': False, 'disable-dram-formula': True, 'cpu-rapl-ref-event': 'RAPL_ENERGY_PKG', 'dram-rapl-ref-event': 'RAPL_ENERGY_DRAM', 'cpu-tdp': 125, 'cpu-base-clock': 100, 'cpu-ratio-min': 10, 'cpu-ratio-base': 23, 'cpu-ratio-max': 32, 'cpu-error-threshold': 2.0, 'dram-error-threshold': 2.0, 'sensor-reports-frequency': 1000, 'learn-min-samples-required': 10, 'learn-history-window-size': 60}}}
INFO:root:SmartWatts version 0.6.0 using PowerAPI version 0.8.1
INFO:root:CPU formula is ENABLED
INFO:root:CPU formula parameters: RAPL_REF=RAPL_ENERGY_PKG ERROR_THRESHOLD=2.0W
INFO:root:DRAM formula is DISABLED
INFO:root:Starting SmartWatts actors...
INFO:root:SmartWatts is now running...
2021-09-02 09:24:45,825 || ERROR || 101 ('cpu_dispatcher', 'sensor', '1') || Minor exception raised, restart actor !
ERROR:('cpu_dispatcher', 'sensor', '1'):Minor exception raised, restart actor !
2021-09-02 09:24:45,826 || ERROR || 98 ('cpu_dispatcher', 'sensor', '0') || Minor exception raised, restart actor !
ERROR:('cpu_dispatcher', 'sensor', '0'):Minor exception raised, restart actor !
Traceback (most recent call last):
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/actor/actor.py", line 130, in run
    self.behaviour(self)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/actor/actor.py", line 222, in _initial_behaviour
    handler.handle_message(msg)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/handler/handler.py", line 63, in handle_message
    self.handle(msg)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/handler.py", line 231, in handle
    self._process_report(msg)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/handler.py", line 214, in _process_report
    power_reports, formula_reports = self._process_oldest_tick()
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/handler.py", line 169, in _process_oldest_tick
    model = self.formula.get_power_model(avg_msr)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/formula.py", line 215, in get_power_model
    return self.models[self._get_frequency_layer(self.compute_pkg_frequency(system_core))]
KeyError: 0

**Comment by altor** [comment]
Hello,
It seems you didn't configure correctly the cpu frequency
What is the model of your CPU ?

**Comment by valentin19** [comment]
Hello,
Thank you, it is indeed a problem of cpu frequency configuration !
