### ISSUE TITLE
Problem to connect with influxdb

### ISSUE THREAD

**Issue by marceloamaral** [powerapi-ng/smartwatts-formula#24]
The problem is when saving the results, while it works fine with mongodb, configuring with influxdb is failing.

The logs shows:
```
Traceback (most recent call last):
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/cli/config_parser.py", line 228, in parse
    conf = self._parse_file(filename)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/cli/config_parser.py", line 166, in _parse_file
    conf = json.load(config_file)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 21 column 5 (char 465)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/__main__.py", line 278, in <module>
    conf = get_config()
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/__main__.py", line 273, in get_config
    return parser.parse()
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/cli/config_parser.py", line 261
, in parse
    logging.error('Configuration Error: JSON Error: ' + exn.msg + ' at line' + exn.lineno + ' colomn ' + exn.colno)
TypeError: can only concatenate str (not "int") to str
```

My configuration is:
```
    {
      "verbose": true,
      "stream": true,
      "input": {
        "puller": {
          "model": "HWPCReport",
          "type": "mongodb",
          "uri": "mongodb://root:admin@smartwatts-mongodb.default",
          "db": "db_sensor",
          "port": 27017,
          "collection": "report_0"
        }
      },
      "output": {
        "pusher_power": {
          "type": "influxdb",
          "model": "PowerReport",
          "uri": "http://smartwatts-influx-influxdb.default",
          "port": "8086",
          "db": "db_out",
        }
      },
      "cpu-frequency-base": 2300,
      "cpu-frequency-min": 1200,
      "cpu-frequency-max": 3600,
      "cpu-error-threshold": 2.0,
      "disable-dram-formula": true,
      "sensor-report-sampling-interval": 1000
    }
```

**Comment by roda82** [comment]
Hello, 
If you remove quotes from the port value it should work, i.e., "port": 8086 instead of "port": "8086". 

Regards,

**Comment by marceloamaral** [comment]
My first try was without the quotes, and then I added it because of the error....

**Comment by marceloamaral** [comment]
Btw, thanks @roda82 for the quick reply!

I tried again without the quotes and I am getting the same error....

**Comment by marceloamaral** [comment]
Found the problem, it was the comma in `"db": "db_out",`
Sorry for that...
