### ISSUE TITLE
crash while calculating the power 

### ISSUE THREAD

**Issue by chakib-belgaid** [powerapi-ng/smartwatts-formula#6]
INFO:root:SmartWatts version 0.4.4 using PowerAPI version 0.6.10
INFO:root:CPU formula is ENABLED
INFO:root:CPU formula parameters: RAPL_REF=RAPL_ENERGY_PKG ERROR_THRESHOLD=2.0W
INFO:root:DRAM formula is DISABLED
INFO:root:Starting SmartWatts actors...
INFO:root:SmartWatts is now running...
Process ('cpu_dispatcher', 'chetemi-2.lille.grid5000.fr', '0'):
Traceback (most recent call last):
  File "/opt/powerapi/.local/lib/python3.7/site-packages/smartwatts/handler.py", line 171, in _process_oldest_tick
    raw_global_power = model.compute_power_estimation(global_core)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/smartwatts/formula.py", line 142, in compute_power_estimation
    return self.model.predict([self._extract_events_value(events)])[0]
  File "/opt/powerapi/.local/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 225, in predict
    return self._decision_function(X)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py", line 789, in _decision_function
    check_is_fitted(self)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 967, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.exceptions.NotFittedError: This ElasticNet instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

During handling of the above exception, another exception occurred:

TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/powerapi/.local/lib/python3.7/site-packages/powerapi/actor/actor.py", line 124, in run
    self.behaviour(self)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/powerapi/actor/actor.py", line 206, in _initial_behaviour
    handler.handle_message(msg)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/powerapi/handler/handler.py", line 63, in handle_message
    self.handle(msg)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/smartwatts/handler.py", line 231, in handle
    self._process_report(msg)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/smartwatts/handler.py", line 213, in _process_report
    power_reports, formula_reports = self._process_oldest_tick()
  File "/opt/powerapi/.local/lib/python3.7/site-packages/smartwatts/handler.py", line 175, in _process_oldest_tick
    model.learn_power_model(self.state.config.min_samples_required, 0.0, self.state.config.cpu_topology.tdp)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/smartwatts/formula.py", line 108, in learn_power_model
    model: Regression = Regression(fit_intercept=fit_intercept, positive=True).fit(self.history.X, self.history.y)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py", line 702, in fit
    copy=X_copied, multi_output=True, y_numeric=True)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 755, in check_X_y
    estimator=estimator)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 531, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/opt/powerapi/.local/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
INFO:root:SmartWatts is shutting down...

**Comment by chakib-belgaid** [comment]
this is the config that i used 
```
CPU_TDP=85
BASE_CPU_RATIO=22
MIN_CPU_RATIO=12
MAX_CPU_RATIO=31
docker run -t -rm --net=host   --name powerapi-formula powerapi/smartwatts-formula \
--input mongodb --model HWPCReport \
-u "mongoserver" -d $INPUT_DB -c $INPUT_COL \
--output mongodb --name power --model PowerReport \
-u "mongoserver" -d $OUTPUT_DB -c $OUTPUT_COL \
--output mongodb --name formula --model FormulaReport \
-u "mongodb://172.16.45.8:27017" -d $OUTPUT_DB -c frep \
--formula smartwatts --cpu-ratio-base $BASE_CPU_RATIO \
--cpu-ratio-min $MIN_CPU_RATIO \
--cpu-ratio-max $MAX_CPU_RATIO \
--sensor-reports-frequency 500 \
--cpu-tdp $CPU_TDP \
--cpu-error-threshold 2.0 \
--dram-error-threshold 2.0 \
--disable-dram-formula

**Comment by altor** [comment]
could you post some example of used input data ?

**Comment by PierreRust** [comment]
I had the same crash this morning, with exactly the same stack trace. Unfortunately the input data is gone and I could not reproduce is yet.

**Comment by PierreRust** [comment]
I had this error again this morning, it's pretty annoying when it happens during a long running tests as you don't get any new power consumption after it (the actor is dead and not restarted). I'll try to look into it.

```
Process ('cpu_dispatcher', 'sensor', '1'):
Traceback (most recent call last):
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/handler.py", line 171, in _process_oldest_tick
    raw_global_power = model.compute_power_estimation(global_core)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/formula.py", line 142, in compute_power_estimation
    return self.model.predict([self._extract_events_value(events)])[0]
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 236, in predict
    return self._decision_function(X)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py", line 881, in _decision_function
    check_is_fitted(self)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1019, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.exceptions.NotFittedError: This ElasticNet instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

During handling of the above exception, another exception occurred:

TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/actor/actor.py", line 125, in run
    self.behaviour(self)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/actor/actor.py", line 207, in _initial_behaviour
    handler.handle_message(msg)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/handler/handler.py", line 63, in handle_message
    self.handle(msg)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/handler.py", line 231, in handle
    self._process_report(msg)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/handler.py", line 213, in _process_report
    power_reports, formula_reports = self._process_oldest_tick()
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/handler.py", line 175, in _process_oldest_tick
    model.learn_power_model(self.state.config.min_samples_required, 0.0, self.state.config.cpu_topology.tdp)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/smartwatts/formula.py", line 108, in learn_power_model
    model: Regression = Regression(fit_intercept=fit_intercept, positive=True).fit(self.history.X, self.history.y)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py", line 759, in fit
    X, y = self._validate_data(X, y, accept_sparse='csc',
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/base.py", line 432, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 795, in check_X_y
    X = check_array(X, accept_sparse=accept_sparse,
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 598, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/opt/powerapi/.local/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

**Comment by altor** [comment]
Hello !
I will make a patch this afternoon to make the actor restart and log its state if this kind of error appears
It will make you able to run long experimentation and help us to understand what is the cause of the crash

**Comment by PierreRust** [comment]
Great news, thanks !

I've done something similar in my fork (except the restart) and I'm running some tests right now, I'll let you now if I get something.

**Comment by PierreRust** [comment]
I just got the error again, it happens when calling `model.fit(self.history.X, self.history.y)`in `PowerModel.learn_power_model` (`formula.py`). WFrom the logs I've added , `fit` is called with the following arguments, where the first entry  in X is an empty list instead of the expected counters : 

```
X => deque([
[], 
[142772.0, 5705658.0, 2836299.0, 6449.0], 
[5833774.0, 279876833.0, 219320665.0, 379247.0], 
[481300.0, 19236870.0, 13401129.0, 39346.0], 
[959953.0, 42640328.0, 37394428.0, 81597.0], 
[54644379.0, 2520994120.0, 2335749402.0, 7399276.0], 
[48665523.0, 2275811799.0, 2274692255.0, 6147603.0], 
[85406949.0, 3761303409.0, 3498405060.0, 6499909.0], 
[113282266.0, 5050132792.0, 5380666586.0, 7726467.0], 
[8816576.0, 388265127.0, 403018165.0, 1303495.0]], maxlen=60) 

y => deque([
0.06768798828125, 
7.2490234375, 
27.88763427734375, 
11.67669677734375, 
11.8779296875, 
23.06402587890625, 
26.65106201171875, 
29.59124755859375, 
36.62939453125, 
23.17083740234375], maxlen=60)
```

**Comment by altor** [comment]
Ok it's maybe a problem with the last report received. If you can, could you log the 6 last received reports ?

The patch for restarting actor to prevent crash will be published tomorrow evening

**Comment by PierreRust** [comment]
My comment above shows the full content of the history (that should be the same thing than the last received reports, isn't it ? ), do you need something else ? 

I'm currently using a dirty workaround where I simply discard empty reports (in `History.store_report`) , it's been running for the last 18 hours without a problem. 

I suspect the sensor might be sending reports without the hwpc, but I'm not sure how we could investigate that (I did not dig into the sensor code for this issue).
